ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

[rule.file-header]
    arguments = ["MIT license · Daniel T. Gorski · dtg \\[at\\] lengo \\[dot\\] org"]
[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.empty-block]
[rule.error-naming]
[rule.error-return]
[rule.error-strings]
[rule.errorf]
[rule.exported]
[rule.if-return]
[rule.increment-decrement]
[rule.indent-error-flow]
#[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.redefines-builtin-id]
[rule.superfluous-else]
[rule.time-naming]
[rule.unexported-return]
[rule.unreachable-code]
[rule.unused-parameter]
[rule.var-declaration]
[rule.var-naming]
[rule.argument-limit]
    arguments = [5]
[rule.atomic]
[rule.bare-return]
[rule.bool-literal-in-expr]
[rule.call-to-gc]
[rule.confusing-naming]
[rule.confusing-results]
[rule.constant-logical-expr]
#[rule.cyclomatic]
#    arguments = [10]
[rule.deep-exit]
[rule.duplicated-imports]
#[rule.flag-parameter]
[rule.function-result-limit]
    arguments = [4]
[rule.import-shadowing]
[rule.line-length-limit]
    arguments = [120]
[rule.modifies-parameter]
[rule.modifies-value-receiver]
[rule.range-val-in-closure]
[rule.struct-tag]
[rule.unhandled-error]
[rule.unnecessary-stmt]
[rule.unused-receiver]
[rule.waitgroup-by-value]

# [rule.add-constant]
#   arguments = [{maxLitCount = "5",allowStrs ="\"\"",allowInts="0,1,2,3,4,5",allowFloats="0.0,0.,1.0,1.,2.0,2."}]
# [rule.max-public-structs]
#    arguments =[5]
